# Generated by Django 5.2.7 on 2025-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
