# Generated by Django 5.2.7 on 2025-10-14 09:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_comment_review_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ddv2w8kgo/image/upload/v1760434762/5b078a59390bb4666df98b49f1cdedd0_t9ys7u.svg', max_length=255, verbose_name='avatar'),
        ),
    ]
