# Generated by Django 5.2.7 on 2025-10-14 09:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='5b078a59390bb4666df98b49f1cdedd0_t9ys7u', max_length=255, verbose_name='avatar'),
        ),
    ]
