# Generated by Django 5.2.7 on 2025-10-14 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_description_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(200)]),
        ),
    ]
